---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    toolkit.fluxcd.io/tenant: migagi-dev
  name: migagi-dev
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    toolkit.fluxcd.io/tenant: migagi-dev
  name: migagi-dev
  namespace: migagi-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    toolkit.fluxcd.io/tenant: migagi-dev
  name: gotk-reconciler
  namespace: migagi-dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: User
    name: gotk:migagi-dev:reconciler
  - kind: ServiceAccount
    name: migagi-dev
    namespace: migagi-dev